### ISSUE TITLE
Feature: Parallel Task Execution with Dependency Graph

### ISSUE THREAD

**Issue by baijum** [baijum/prompter#2]
## Feature Description

Enable running multiple independent tasks simultaneously with a DAG (Directed Acyclic Graph) based dependency system to dramatically improve workflow execution time and resource utilization.

## Problem Statement

Currently, Prompter executes tasks sequentially, which can be inefficient when:
- Multiple tasks have no dependencies on each other
- Long-running tasks block the execution of unrelated tasks
- Resources (CPU, memory, API calls) are underutilized
- Complex workflows with many independent branches take unnecessarily long

### Core Features

1. **Dependency Graph Definition**
   ```toml
   [[tasks]]
   name = "lint_frontend"
   prompt = "Run frontend linting"
   depends_on = []  # Can run immediately
   
   [[tasks]]
   name = "lint_backend" 
   prompt = "Run backend linting"
   depends_on = []  # Can run immediately
   
   [[tasks]]
   name = "fix_all_issues"
   prompt = "Fix issues from both linting reports"
   depends_on = ["lint_frontend", "lint_backend"]  # Waits for both
   ```

2. **Parallel Execution Engine**
   - Worker pool with configurable concurrency limit
   - Resource-aware scheduling (memory/CPU tracking)
   - API rate limit management for Claude calls
   - Queue-based task distribution

3. **Execution Strategies**
   - `max_parallel_tasks`: Global concurrency limit
   - `resource_limits`: Per-task resource requirements
   - `priority`: Task prioritization for scheduling
   - `exclusive`: Tasks that must run alone

### Technical Implementation

1. **Task Graph Construction**
   - Build DAG from task dependencies
   - Detect circular dependencies
   - Topological sorting for execution order
   - Dynamic graph updates during execution

2. **Execution Coordinator**
   ```python
   class ParallelTaskCoordinator:
       async def execute_workflow(self, tasks: List[Task]):
           graph = build_dependency_graph(tasks)
           ready_queue = find_ready_tasks(graph)
           
           async with anyio.create_task_group() as tg:
               while not all_tasks_complete(graph):
                   for task in ready_queue:
                       if can_schedule(task, resource_pool):
                           tg.start_soon(execute_task, task)
                   
                   # Wait for task completion and update graph
                   completed = await wait_for_any_completion()
                   update_graph_and_queue(graph, completed)
   ```

3. **Resource Management**
   - Track Claude API usage across parallel tasks
   - Memory/CPU monitoring per task
   - Automatic backpressure when resources constrained
   - Fair scheduling algorithm

### Configuration Example

```toml
[execution]
max_parallel_tasks = 4
total_memory_limit = "8GB"
claude_api_calls_per_minute = 10

[[tasks]]
name = "analyze_module_a"
prompt = "Analyze and document module A"
depends_on = []
resource_requirements = { memory = "2GB", exclusive_claude = false }

[[tasks]]
name = "analyze_module_b"
prompt = "Analyze and document module B"
depends_on = []
resource_requirements = { memory = "2GB", exclusive_claude = false }

[[tasks]]
name = "generate_summary"
prompt = "Create summary report from all analyses"
depends_on = ["analyze_module_a", "analyze_module_b"]
resource_requirements = { memory = "1GB", exclusive_claude = true }
```

### UI/UX Considerations

1. **Progress Visualization**
   - Real-time graph visualization showing task states
   - Progress bars for parallel execution
   - Resource utilization meters
   - Estimated time to completion

2. **Debugging Support**
   - Parallel execution trace logs
   - Task timing breakdowns
   - Resource contention warnings
   - Deadlock detection

### Benefits

1. **Performance**
   - 3-5x speedup for workflows with parallel tasks
   - Better resource utilization
   - Reduced total execution time

2. **Scalability**
   - Handle larger, more complex workflows
   - Efficient use of Claude API quota
   - Support for distributed execution (future)

3. **Flexibility**
   - Mix sequential and parallel execution
   - Dynamic task generation
   - Conditional parallel branches

### Acceptance Criteria

- [ ] Tasks can declare dependencies on other tasks
- [ ] Independent tasks execute in parallel up to concurrency limit
- [ ] Circular dependency detection prevents invalid configurations
- [ ] Resource limits are respected during parallel execution
- [ ] State management correctly handles parallel task updates
- [ ] CLI shows parallel execution progress clearly
- [ ] Documentation includes parallel execution examples
- [ ] Tests cover various parallel execution scenarios

### Related Issues

- Would complement Web Dashboard for visualization
- Enhances Multi-Agent feature with parallel agent coordination

### Implementation Priority

High - This is a foundational feature that would significantly improve Prompter's performance and enable more complex workflows.

**Comment by baijum** [comment]
✅ **This feature has been fully implemented\!**

## Implementation Summary

### Core Features Delivered:
1. **Dependency Graph System** ✅
   - Tasks can declare dependencies via `depends_on` field
   - Full DAG implementation with cycle detection
   - Topological sorting for execution order

2. **Parallel Execution Engine** ✅
   - `ParallelTaskCoordinator` with configurable worker pool
   - `max_parallel_tasks` setting (default: 4)
   - Resource-aware scheduling with `ResourcePool`
   - Queue-based task distribution

3. **Configuration Support** ✅
   ```toml
   [settings]
   max_parallel_tasks = 4
   enable_parallel = true
   
   [[tasks]]
   name = "task1"
   depends_on = []
   
   [[tasks]]
   name = "task2"
   depends_on = ["task1"]
   ```

4. **Progress Visualization** ✅
   - Real-time progress display with Rich library
   - Shows task states, dependencies, and parallel execution
   - Resource utilization tracking
   - Graceful degradation for non-TTY environments

### Key Implementation Files:
- `src/prompter/parallel_coordinator.py` - Core parallel execution logic
- `src/prompter/task_graph.py` - DAG implementation
- `src/prompter/progress_display.py` - Real-time visualization
- `src/prompter/config.py` - Extended with dependency support

### Test Coverage:
- `tests/test_parallel_execution.py` - Unit tests
- `tests/test_parallel_integration.py` - Integration tests
- `tests/test_parallel_integration_simple.py` - Simple integration tests
- `tests/test_task_graph.py` - Graph algorithm tests

### Performance:
- Successfully executes independent tasks in parallel
- Respects resource limits and max_parallel_tasks setting
- Handles complex dependency patterns (diamond, wide parallel, mixed)
- Graceful failure handling with dependency-aware task skipping

All acceptance criteria have been met. The feature is ready for use\!
