### ISSUE TITLE
Feature: Task Template Marketplace

### ISSUE THREAD

**Issue by baijum** [baijum/prompter#5]
## Feature Description

Create a community-driven marketplace for sharing, discovering, and reusing Prompter task templates, enabling users to leverage proven workflows and contribute their own solutions.

## Problem Statement

Currently, users must:
- Write all task configurations from scratch
- Rediscover solutions others have already created
- Lack access to community best practices
- Cannot easily share successful workflows
- Miss optimization opportunities from collective experience
- Duplicate effort across similar projects

### Core Components

1. **Template Repository System**
   - Central registry for templates
   - Version control for templates
   - Categorization and tagging
   - Usage statistics tracking
   - Template validation system

2. **CLI Integration**
   ```bash
   # Browse and install templates
   prompter template search "python linting"
   prompter template install security-audit@v2.1
   prompter template info nodejs-ci-cd
   
   # Create and share templates
   prompter template create my-workflow.toml
   prompter template publish --name "rails-upgrade" --version 1.0
   ```

3. **Web Portal**
   - Browse templates by category
   - Search and filter capabilities
   - User ratings and reviews
   - Documentation and examples
   - One-click installation

### Template Structure

```toml
# .prompter-template.toml
[template]
name = "python-security-audit"
version = "2.1.0"
author = "security-team"
description = "Comprehensive security audit for Python projects"
tags = ["security", "python", "audit", "dependencies"]
min_prompter_version = "1.0.0"

[template.parameters]
# Configurable parameters with defaults
scan_depth = { type = "string", default = "full", options = ["quick", "standard", "full"] }
include_deps = { type = "boolean", default = true }
severity_threshold = { type = "string", default = "medium" }

[template.requirements]
# Required tools/commands
commands = ["python", "pip", "safety", "bandit"]
files = ["requirements.txt", "setup.py"]

# Template tasks with parameter interpolation
[[tasks]]
name = "dependency_scan"
prompt = "Scan dependencies for vulnerabilities using safety with {{severity_threshold}} threshold"
verify_command = "safety check --json"
on_failure = "report_issues"

[[tasks]]
name = "code_security_scan"
prompt = "Run bandit security linter on codebase with {{scan_depth}} analysis"
verify_command = "bandit -r . -f json"
on_success = "generate_report"
```

### Template Categories

1. **Language Specific**
   - Python: linting, testing, packaging
   - JavaScript: build, test, deploy
   - Go: modules, testing, benchmarks
   - Rust: cargo workflows, security

2. **Framework Specific**
   - Django: migrations, security, optimization
   - React: component testing, bundle analysis
   - Rails: upgrades, performance
   - FastAPI: API testing, documentation

3. **DevOps & CI/CD**
   - Docker: build, scan, optimize
   - Kubernetes: deployments, security
   - GitHub Actions: workflow generation
   - AWS/GCP/Azure: cloud deployments

4. **Security & Compliance**
   - Dependency scanning
   - Code security analysis
   - License compliance
   - Secret detection

5. **Code Quality**
   - Comprehensive linting
   - Test coverage improvement
   - Documentation generation
   - Code complexity reduction

### Marketplace Features

1. **Template Discovery**
   ```bash
   $ prompter template search django --sort=popular
   
   Found 23 templates:
   
   1. django-upgrade-assistant (★ 4.8, 1.2k uses)
      Automated Django version upgrades with testing
      
   2. django-security-hardening (★ 4.7, 890 uses)
      Security best practices implementation
      
   3. django-performance-tuner (★ 4.5, 623 uses)
      Database and cache optimization
   ```

2. **Template Composition**
   ```toml
   # Combine multiple templates
   [imports]
   templates = [
     "python-linting@2.0",
     "security-audit@1.5",
     "test-coverage@1.0"
   ]
   
   # Override specific settings
   [overrides."python-linting"]
   max_line_length = 100
   ```

3. **Parameter Wizards**
   ```bash
   $ prompter template init django-project
   
   Welcome to django-project template v3.2
   
   ? Project name: my-awesome-app
   ? Python version: 3.11
   ? Include Docker setup? Yes
   ? Database backend: PostgreSQL
   ? Add CI/CD pipeline? Yes
   
   ✓ Template configured and saved to my-awesome-app.toml
   ```

### Community Features

1. **User Contributions**
   - GitHub/GitLab integration
   - Pull request workflow
   - Automated testing
   - Security scanning
   - License verification

2. **Quality Assurance**
   - Automated template validation
   - Community review process
   - Trusted publisher program
   - Security audit requirements
   - Version compatibility testing

3. **Analytics & Insights**
   - Usage statistics
   - Success/failure rates
   - User feedback scores
   - Performance metrics
   - Popular combinations

### Technical Implementation

1. **Registry Backend**
   ```python
   class TemplateRegistry:
       def __init__(self):
           self.storage = S3Storage()  # or GitHub releases
           self.database = PostgreSQL()  # metadata
           self.cache = Redis()  # popular templates
       
       async def publish_template(self, template: Template):
           # Validate template structure
           await self.validator.check(template)
           
           # Run security scans
           await self.security.scan(template)
           
           # Store template and metadata
           await self.storage.upload(template)
           await self.database.index(template)
           
           # Update search index
           await self.search.index(template)
   ```

2. **Local Template Cache**
   ```
   ~/.prompter/
   ├── templates/
   │   ├── django-upgrade@2.1.0/
   │   ├── react-testing@1.5.2/
   │   └── security-audit@3.0.0/
   ├── template-cache.json
   └── template-config.toml
   ```

3. **Template Validation**
   - TOML syntax validation
   - Task dependency checking
   - Parameter type validation
   - Command availability verification
   - Security policy compliance

### Monetization Options (Future)

1. **Premium Templates**
   - Enterprise-grade workflows
   - Certified security templates
   - Compliance frameworks
   - Priority support

2. **Private Registries**
   - Corporate template sharing
   - Access control
   - Audit logging
   - SLA guarantees

### Benefits

1. **Productivity**
   - Instant access to proven solutions
   - No reinventing the wheel
   - Learn from community
   - Rapid project setup

2. **Quality**
   - Battle-tested workflows
   - Best practices built-in
   - Continuous improvements
   - Peer review process

3. **Collaboration**
   - Share team workflows
   - Contribute to community
   - Build reputation
   - Learn from others

### Acceptance Criteria

- [ ] CLI commands for search/install/publish work
- [ ] Template validation ensures quality
- [ ] Version management handles updates
- [ ] Parameter system supports customization
- [ ] Local cache improves performance
- [ ] Search functionality is fast and relevant
- [ ] Documentation generator creates README
- [ ] Security scanning prevents malicious templates
- [ ] Analytics track template usage
- [ ] Web portal provides easy browsing

### Related Issues

- Integrates with #3 (Dashboard) for template browsing
- Uses #4 (Recovery) patterns in templates
- Enables #5 (Multi-Agent) workflow sharing

### Implementation Priority

Medium-High - While not critical for core functionality, a template marketplace would dramatically accelerate adoption and create a valuable community ecosystem around Prompter.
